# Generated by Django 4.0.6 on 2022-09-16 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_cliente', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('apellido_cliente', models.CharField(max_length=100)),
                ('celular_cliente', models.IntegerField()),
                ('fecha_nacimiento', models.DateField(default='2000-01-01')),
                ('direccion', models.CharField(max_length=125)),
            ],
        ),
        migrations.CreateModel(
            name='Envios',
            fields=[
                ('id_envios', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_envio', models.DateField(default='2000-01-01')),
                ('direccion_envio', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('id_marca', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_marca', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MediosDePagos',
            fields=[
                ('id_medio_pago', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_medio_pago', models.CharField(max_length=50)),
                ('estado_medio_pago', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id_pedido', models.IntegerField(primary_key=True, serialize=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='paginaWeb.clientes')),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id_roles', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id_venta', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('envio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='paginaWeb.envios')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='paginaWeb.pedidos')),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_correo', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('contrasena', models.CharField(max_length=14)),
                ('roles', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='paginaWeb.roles')),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_producto', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=100)),
                ('stock', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('descripcion', models.TextField(default='')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='paginaWeb.marcas')),
            ],
        ),
        migrations.CreateModel(
            name='PedidosProductos',
            fields=[
                ('id_pedidos_productos', models.IntegerField(primary_key=True, serialize=False)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='paginaWeb.pedidos')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='paginaWeb.productos')),
            ],
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id_pago', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_pagos', models.DateTimeField(auto_now=True)),
                ('medio_pago', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='paginaWeb.mediosdepagos')),
            ],
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id_historial', models.IntegerField(primary_key=True, serialize=False)),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='paginaWeb.pagos')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='paginaWeb.ventas')),
            ],
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id_empleado', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_empleado', models.CharField(max_length=100)),
                ('apellido_empleado', models.CharField(max_length=100)),
                ('celular_empleado', models.IntegerField()),
                ('fecha_nacimiento', models.DateField(default='2000-01-01')),
                ('eps', models.CharField(max_length=50)),
                ('correo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='paginaWeb.usuarios')),
            ],
        ),
        migrations.AddField(
            model_name='clientes',
            name='correo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='paginaWeb.usuarios'),
        ),
    ]
