# Generated by Django 4.0.6 on 2022-10-28 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id_categoria', models.IntegerField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('id_marca', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_marca', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MediosDePagos',
            fields=[
                ('id_medio_pago', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_medio_pago', models.CharField(max_length=50)),
                ('estado_medio_pago', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('cedula', models.IntegerField(primary_key=True, serialize=False)),
                ('foto', models.ImageField(default='RUN/fotoUsuario/defaultFoto.png', upload_to='RUN/fotoUsuario')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=12)),
                ('fecha_nacimiento', models.DateField(default='2000-01-01')),
                ('direccion', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=100)),
                ('contrasena', models.CharField(max_length=235)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id_roles', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=100)),
                ('descripcion', models.TextField(default='Descripción del rol...')),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id_venta', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_envio', models.DateTimeField(auto_now=True)),
                ('direccion', models.CharField(max_length=100)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='paginaWeb.personas')),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_producto', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=100)),
                ('stock', models.FloatField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('descripcion', models.TextField(default='')),
                ('palabras_clave', models.CharField(max_length=100)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='paginaWeb.categorias')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='paginaWeb.marcas')),
            ],
        ),
        migrations.AddField(
            model_name='personas',
            name='roles',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='paginaWeb.roles'),
        ),
        migrations.CreateModel(
            name='PedidosProductos',
            fields=[
                ('id_pedidos_productos', models.IntegerField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='paginaWeb.productos')),
                ('ventas', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='paginaWeb.ventas')),
            ],
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id_pago', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_pagos', models.DateTimeField(auto_now=True)),
                ('medio_pago', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='paginaWeb.mediosdepagos')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='paginaWeb.ventas')),
            ],
        ),
        migrations.CreateModel(
            name='Imagenes',
            fields=[
                ('id_imagen', models.IntegerField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(default='RUN/imagProductos/default.png', upload_to='RUN/imagProductos')),
                ('productos', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='paginaWeb.productos')),
            ],
        ),
    ]
