# Generated by Django 4.0.6 on 2022-11-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginaWeb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personas',
            name='tipo',
        ),
        migrations.AddField(
            model_name='marcas',
            name='imagen',
            field=models.ImageField(default='RUN/fotoMarcas/default.png', upload_to='RUN/fotoMarcas'),
        ),
    ]
