# Generated by Django 4.0.6 on 2022-09-24 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginaWeb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleados',
            name='direccion_empleado',
            field=models.CharField(default='Cerca de la empresa', max_length=100),
        ),
    ]
