# Generated by Django 4.0.6 on 2022-10-11 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginaWeb', '0002_empleados_direccion_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(default='RUN/imgProductos/default.png', upload_to='RUN/imgProductos'),
        ),
    ]
