# Generated by Django 4.0.6 on 2022-11-24 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginaWeb', '0002_remove_personas_tipo_marcas_imagen'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PedidosProductos',
            new_name='Pedidos',
        ),
        migrations.RenameField(
            model_name='pedidos',
            old_name='id_pedidos_productos',
            new_name='id_pedido',
        ),
    ]
