# Generated by Django 4.0.6 on 2022-11-24 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginaWeb', '0003_rename_pedidosproductos_pedidos_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidos',
            old_name='ventas',
            new_name='venta',
        ),
    ]
